name: ci

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - src/**

env:
  TEST_TAG: eytes/ideabox_frontend:ci-test
  LATEST_TAG: eytes/ideabox_frontend:latest

jobs:
  linting_and_type_checking:
    uses: "./.github/workflows/lining_and_type_checking.yml"

  docker:
    needs: [ linting_and_type_checking ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and export a test image to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test run of the image
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
